{% set name = "thztools" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thztools-{{ version }}.tar.gz
  sha256: d94e7707041fcf0af62255bf3b464f0a9b22fa72a3af3daf252f38c6d4a68420

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - scipy

test:
  imports:
    - thztools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/thztools/
  summary: Data analysis software tools for terahertz time-domain spectroscopy (THz-TDS)
  dev_url: https://github.com/dodge-research-group/thztools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsdodge
